# Generated by Django 5.2.7 on 2025-10-19 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('career_en', models.CharField(max_length=200)),
                ('career_es', models.CharField(max_length=200)),
                ('role_en', models.CharField(max_length=100)),
                ('role_es', models.CharField(max_length=100)),
                ('charge_en', models.CharField(max_length=200)),
                ('charge_es', models.CharField(max_length=200)),
                ('image_url', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='members/')),
            ],
            options={
                'db_table': 'members',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, unique=True)),
                ('name_es', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'teams',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('member', models.OneToOneField(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to='api.member')),
            ],
            options={
                'db_table': 'admins',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=300, unique=True)),
                ('icon_url', models.CharField(max_length=300)),
                ('member', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='api.member')),
            ],
            options={
                'db_table': 'red_social',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=300, unique=True)),
                ('title_es', models.CharField(max_length=300, unique=True)),
                ('content_en', models.TextField()),
                ('content_es', models.TextField()),
                ('publication_date', models.DateField()),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('team', models.ForeignKey(blank=True, db_column='team_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='api.team')),
            ],
            options={
                'db_table': 'publications',
                'ordering': ['-publication_date', 'id'],
            },
        ),
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.team'),
        ),
    ]
