from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'red_social'
    ) THEN
        IF EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = 'red_social' AND column_name = 'link'
        ) THEN
            ALTER TABLE red_social RENAME COLUMN link TO url;
        END IF;

        IF EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = 'red_social' AND column_name = 'icon_url'
        ) THEN
            ALTER TABLE red_social RENAME COLUMN icon_url TO platform;
        END IF;

        ALTER TABLE red_social ALTER COLUMN platform TYPE varchar(20);
    ELSE
        CREATE TABLE red_social (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            url varchar(300) NOT NULL UNIQUE,
            platform varchar(20) NOT NULL,
            member_id bigint NOT NULL REFERENCES members(id) DEFERRABLE INITIALLY DEFERRED
        );

        CREATE INDEX red_social_member_id_idx ON red_social(member_id);
    END IF;
END $$;
                    """,
                    reverse_sql="""
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'red_social'
    ) THEN
        IF EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = 'red_social' AND column_name = 'platform'
        ) AND NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = 'red_social' AND column_name = 'icon_url'
        ) THEN
            ALTER TABLE red_social ALTER COLUMN platform TYPE varchar(300);
            ALTER TABLE red_social RENAME COLUMN platform TO icon_url;
        END IF;

        IF EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = 'red_social' AND column_name = 'url'
        ) AND NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = 'red_social' AND column_name = 'link'
        ) THEN
            ALTER TABLE red_social RENAME COLUMN url TO link;
        END IF;
    END IF;
END $$;
                    """,
                )
            ],
            state_operations=[
                migrations.RenameField(
                    model_name='redsocial',
                    old_name='link',
                    new_name='url',
                ),
                migrations.RenameField(
                    model_name='redsocial',
                    old_name='icon_url',
                    new_name='platform',
                ),
                migrations.AlterField(
                    model_name='redsocial',
                    name='platform',
                    field=models.CharField(
                        choices=[
                            ('behance', 'Behance'),
                            ('portfolio', 'Portfolio'),
                            ('github', 'GitHub'),
                            ('instagram', 'Instagram'),
                            ('linkedin', 'LinkedIn'),
                            ('x', 'X'),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
