# Generated by Django 5.2.7 on 2026-04-02 08:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_member_role_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='name_en',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='publication',
            name='name_es',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='PaymentCheckoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider', models.CharField(default='stripe', max_length=30)),
                ('provider_session_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('item_type', models.CharField(choices=[('membership', 'Membership'), ('product', 'Product')], max_length=20)),
                ('item_id', models.CharField(max_length=100)),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='created', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_sessions', to='api.member')),
            ],
            options={
                'db_table': 'payment_checkout_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='stripe', max_length=30)),
                ('provider_event_id', models.CharField(max_length=120, unique=True)),
                ('event_type', models.CharField(max_length=120)),
                ('signature_verified', models.BooleanField(default=False)),
                ('payload_hash', models.CharField(max_length=64)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payment_webhook_events',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['provider', 'event_type'], name='pay_webhook_prov_type_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=120)),
                ('severity', models.CharField(default='info', max_length=20)),
                ('ip_address', models.CharField(blank=True, max_length=64, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.member')),
            ],
            options={
                'db_table': 'security_audit_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name='Admin',
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='paymentcheckoutsession',
            index=models.Index(fields=['provider', 'status'], name='pay_sess_prov_status_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentcheckoutsession',
            index=models.Index(fields=['member', 'created_at'], name='pay_sess_member_created_idx'),
        ),
        migrations.AddIndex(
            model_name='securityauditevent',
            index=models.Index(fields=['event_type', 'created_at'], name='sec_audit_type_created_idx'),
        ),
        migrations.AddIndex(
            model_name='securityauditevent',
            index=models.Index(fields=['severity', 'created_at'], name='sec_audit_sev_created_idx'),
        ),
    ]
