# Generated by Django 4.2.7 on 2026-04-09 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_enforce_member_user_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcheckoutsession',
            name='item_type',
            field=models.CharField(choices=[('membership', 'Membership'), ('product', 'Product'), ('donation', 'Donation')], max_length=20),
        ),
        migrations.CreateModel(
            name='TeamLeaderWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team')),
            ],
            options={
                'verbose_name': 'Team Leader Whitelist',
                'verbose_name_plural': 'Team Leader Whitelists',
                'db_table': 'team_leader_whitelist',
                'ordering': ['team__name_en', 'email'],
            },
        ),
    ]
