# Generated by Django 4.2.7 on 2026-04-09 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_alter_paymentcheckoutsession_item_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamleaderwhitelist',
            options={'ordering': ['team__name_en', 'email'], 'verbose_name': 'Team Leader Whitelist (DEPRECATED)', 'verbose_name_plural': 'Team Leader Whitelists (DEPRECATED)'},
        ),
        migrations.CreateModel(
            name='TeamLeaderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('is_whitelist_verified', models.BooleanField(default=False)),
                ('is_admin_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_verification', 'Pending Email Verification'), ('pending_approval', 'Pending Admin Approval'), ('approved', 'Approved'), ('denied', 'Denied'), ('expired', 'Expired')], default='pending_verification', max_length=20)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('requested_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team')),
            ],
            options={
                'verbose_name': 'Team Leader Request',
                'verbose_name_plural': 'Team Leader Requests',
                'db_table': 'team_leader_requests',
                'ordering': ['-created_at'],
                'unique_together': {('email', 'requested_team')},
            },
        ),
    ]
