export const CAREER_OPTIONS = [
  { key: 'business_administration', en: 'Business Administration', es: 'Administración de Empresas' },
  { key: 'anthropology', en: 'Anthropology', es: 'Antropología' },
  { key: 'architecture', en: 'Architecture', es: 'Arquitectura' },
  { key: 'art', en: 'Art', es: 'Arte' },
  { key: 'biology', en: 'Biology', es: 'Biología' },
  { key: 'data_science', en: 'Data Science', es: 'Ciencia de Datos' },
  { key: 'political_science', en: 'Political Science', es: 'Ciencia Política' },
  { key: 'law', en: 'Law', es: 'Derecho' },
  { key: 'design', en: 'Design', es: 'Diseño' },
  { key: 'economics', en: 'Economics', es: 'Economía' },
  { key: 'global_studies', en: 'Global Studies', es: 'Estudios Globales' },
  { key: 'philosophy', en: 'Philosophy', es: 'Filosofía' },
  { key: 'physics', en: 'Physics', es: 'Física' },
  { key: 'geosciences', en: 'Geosciences', es: 'Geociencias' },
  { key: 'history', en: 'History', es: 'Historia' },
  { key: 'art_history', en: 'Art History', es: 'Historia del Arte' },
  { key: 'environmental_engineering', en: 'Environmental Engineering', es: 'Ingeniería Ambiental' },
  { key: 'biomedical_engineering', en: 'Biomedical Engineering', es: 'Ingeniería Biomédica' },
  { key: 'civil_engineering', en: 'Civil Engineering', es: 'Ingeniería Civil' },
  {
    key: 'systems_and_computer_engineering',
    en: 'Systems and Computer Engineering',
    es: 'Ingeniería de Sistemas y Computación',
  },
  { key: 'electrical_engineering', en: 'Electrical Engineering', es: 'Ingeniería Eléctrica' },
  { key: 'electronic_engineering', en: 'Electronic Engineering', es: 'Ingeniería Electrónica' },
  { key: 'industrial_engineering', en: 'Industrial Engineering', es: 'Ingeniería Industrial' },
  { key: 'mechanical_engineering', en: 'Mechanical Engineering', es: 'Ingeniería Mecánica' },
  { key: 'chemical_engineering', en: 'Chemical Engineering', es: 'Ingeniería Química' },
  { key: 'languages_and_culture', en: 'Languages and Culture', es: 'Lenguas y Cultura' },
  { key: 'bachelor_of_arts', en: 'Bachelor of Arts', es: 'Licenciatura en Artes' },
  { key: 'bachelor_of_biology', en: 'Bachelor of Biology', es: 'Licenciatura en Biología' },
  {
    key: 'bachelor_of_early_childhood_education',
    en: 'Bachelor of Early Childhood Education',
    es: 'Licenciatura en Educación Infantil',
  },
  {
    key: 'bachelor_of_spanish_and_philology',
    en: 'Bachelor of Spanish and Philology',
    es: 'Licenciatura en Español y Filología',
  },
  { key: 'bachelor_of_philosophy', en: 'Bachelor of Philosophy', es: 'Licenciatura en Filosofía' },
  { key: 'bachelor_of_physics', en: 'Bachelor of Physics', es: 'Licenciatura en Física' },
  { key: 'bachelor_of_history', en: 'Bachelor of History', es: 'Licenciatura en Historia' },
  { key: 'bachelor_of_mathematics', en: 'Bachelor of Mathematics', es: 'Licenciatura en Matemáticas' },
  { key: 'bachelor_of_chemistry', en: 'Bachelor of Chemistry', es: 'Licenciatura en Química' },
  { key: 'literature', en: 'Literature', es: 'Literatura' },
  { key: 'mathematics', en: 'Mathematics', es: 'Matemáticas' },
  { key: 'medicine', en: 'Medicine', es: 'Medicina' },
  { key: 'microbiology', en: 'Microbiology', es: 'Microbiología' },
  { key: 'music', en: 'Music', es: 'Música' },
  { key: 'digital_narratives', en: 'Digital Narratives', es: 'Narrativas Digitales' },
  { key: 'psychology', en: 'Psychology', es: 'Psicología' },
  { key: 'chemistry', en: 'Chemistry', es: 'Química' },
];

export const getLocalizedCareerLabel = (career, language) => (language === 'es' ? career.es : career.en);