"""
Django settings for candelaria_project project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import parse_qs, urlparse
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured('SECRET_KEY environment variable is required')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').strip().lower() == 'true'

def _parse_csv_env(var_name, default=''):
    return [
        item.strip()
        for item in os.getenv(var_name, default).split(',')
        if item.strip()
    ]


ALLOWED_HOSTS = _parse_csv_env('ALLOWED_HOSTS', 'localhost,127.0.0.1,.vercel.app')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party apps
    'rest_framework',
    'corsheaders',
    # Local apps
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware
    'api.middleware.ApiContentTypeGuardMiddleware',
    'django.middleware.common.CommonMiddleware',
    'api.middleware.ApiSecurityHeadersMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'candelaria_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'candelaria_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

def build_database_settings():
    database_url = os.getenv('DATABASE_URL', '').strip()

    if database_url:
        parsed = urlparse(database_url)
        query = parse_qs(parsed.query)
        sslmode = query.get('sslmode', [os.getenv('DB_SSLMODE', 'require')])[0]

        config = {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': (parsed.path or '').lstrip('/') or os.getenv('DB_NAME', 'candelaria_db'),
            'USER': parsed.username or os.getenv('DB_USER', 'postgres'),
            'PASSWORD': parsed.password or os.getenv('DB_PASSWORD', ''),
            'HOST': parsed.hostname or os.getenv('DB_HOST', 'localhost'),
            'PORT': str(parsed.port or os.getenv('DB_PORT', '5432')),
        }

        if sslmode:
            config['OPTIONS'] = {'sslmode': sslmode}

        return {'default': config}

    sslmode = os.getenv('DB_SSLMODE', '').strip()
    config = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'candelaria_db'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }

    if sslmode:
        config['OPTIONS'] = {'sslmode': sslmode}

    return {'default': config}


DATABASES = build_database_settings()

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'candelaria-security-cache',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Configuration
CORS_ALLOWED_ORIGINS = _parse_csv_env(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173,http://localhost:5174,http://127.0.0.1:5174'
)

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CSRF_TRUSTED_ORIGINS = _parse_csv_env('CSRF_TRUSTED_ORIGINS')

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': os.getenv('THROTTLE_ANON_RATE', '120/hour'),
        'user': os.getenv('THROTTLE_USER_RATE', '1000/hour'),
        'burst': os.getenv('THROTTLE_BURST_RATE', '60/minute'),
        'auth': os.getenv('THROTTLE_AUTH_RATE', '10/minute'),
    },
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
}

# JWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# Media files (for uploaded images)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

SUPABASE_URL = (os.getenv('SUPABASE_URL') or os.getenv('VITE_SUPABASE_URL') or '').strip()
SUPABASE_SERVICE_ROLE_KEY = os.getenv('SUPABASE_SERVICE_ROLE_KEY', '').strip()
SUPABASE_STORAGE_BUCKET = os.getenv('SUPABASE_STORAGE_BUCKET', 'media').strip() or 'media'
USE_SUPABASE_STORAGE = bool(SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY)

if USE_SUPABASE_STORAGE:
    STORAGES = {
        'default': {
            'BACKEND': 'api.storage.SupabaseStorage',
            'OPTIONS': {
                'bucket_name': SUPABASE_STORAGE_BUCKET,
                'supabase_url': SUPABASE_URL,
                'service_role_key': SUPABASE_SERVICE_ROLE_KEY,
            },
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }

# Frontend URL used in password reset emails
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173')

# Email settings for password reset
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@candelaria.local')

# Payment integration settings (secrets are read from environment only).
PAYMENT_PROVIDER = os.getenv('PAYMENT_PROVIDER', 'stripe').strip().lower()
PAYMENT_PUBLIC_KEY = os.getenv('PAYMENT_PUBLIC_KEY', '').strip()
PAYMENT_SECRET_KEY = os.getenv('PAYMENT_SECRET_KEY', '').strip()
PAYMENT_WEBHOOK_SECRET = os.getenv('PAYMENT_WEBHOOK_SECRET', '').strip()
PAYMENT_WEBHOOK_TOLERANCE_SECONDS = int(os.getenv('PAYMENT_WEBHOOK_TOLERANCE_SECONDS', '300'))
PAYMENT_DEFAULT_CURRENCY = os.getenv('PAYMENT_DEFAULT_CURRENCY', 'usd').strip().lower()
PAYMENT_MIN_AMOUNT_CENTS = int(os.getenv('PAYMENT_MIN_AMOUNT_CENTS', '100'))
PAYMENT_MAX_AMOUNT_CENTS = int(os.getenv('PAYMENT_MAX_AMOUNT_CENTS', '5000000'))
PURCHASES_ENABLED = os.getenv(
    'PURCHASES_ENABLED',
    'True' if DEBUG else 'False'
).strip().lower() in ('true', '1', 'yes')

if not DEBUG and PURCHASES_ENABLED and PAYMENT_PROVIDER == 'stripe':
    if not PAYMENT_PUBLIC_KEY or not PAYMENT_SECRET_KEY or not PAYMENT_WEBHOOK_SECRET:
        raise ImproperlyConfigured(
            'PAYMENT_PUBLIC_KEY, PAYMENT_SECRET_KEY and PAYMENT_WEBHOOK_SECRET are required in production.'
        )

# PayU integration settings (used when PAYMENT_PROVIDER='payu').
PAYU_MERCHANT_ID = os.getenv('PAYU_MERCHANT_ID', '').strip()
PAYU_ACCOUNT_ID = os.getenv('PAYU_ACCOUNT_ID', '').strip()
PAYU_API_KEY = os.getenv('PAYU_API_KEY', '').strip()
PAYU_API_LOGIN = os.getenv('PAYU_API_LOGIN', '').strip()
PAYU_TEST_MODE = os.getenv('PAYU_TEST_MODE', 'True').strip().lower() not in ('false', '0', 'no')

if not DEBUG and PURCHASES_ENABLED and PAYMENT_PROVIDER == 'payu':
    if not PAYU_MERCHANT_ID or not PAYU_API_KEY or not PAYU_API_LOGIN:
        raise ImproperlyConfigured(
            'PAYU_MERCHANT_ID, PAYU_API_KEY and PAYU_API_LOGIN are required in production when using PayU.'
        )

# Login brute-force controls.
AUTH_MAX_ATTEMPTS = int(os.getenv('AUTH_MAX_ATTEMPTS', '8'))
AUTH_ATTEMPT_WINDOW_SECONDS = int(os.getenv('AUTH_ATTEMPT_WINDOW_SECONDS', '900'))

# Upload limits help mitigate payload abuse attempts.
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv('DATA_UPLOAD_MAX_MEMORY_SIZE', str(2 * 1024 * 1024)))
FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv('FILE_UPLOAD_MAX_MEMORY_SIZE', str(5 * 1024 * 1024)))

if not DEBUG:
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'True').strip().lower() == 'true'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_REFERRER_POLICY = 'same-origin'
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Team Leader Security Configuration
TEAM_LEADER_WHITELIST_ENABLED = os.getenv('TEAM_LEADER_WHITELIST_ENABLED', 'true').lower() == 'true'
TEAM_LEADER_AUTO_ASSIGN = os.getenv('TEAM_LEADER_AUTO_ASSIGN', 'false').lower() == 'true'
ADMIN_APPROVAL_REQUIRED = os.getenv('ADMIN_APPROVAL_REQUIRED', 'true').lower() == 'true'

# Security Logging Configuration (Vercel-compatible)
# Only create logs directory in development, use console logging in production
if DEBUG:
    # Local development - use file logging
    import os
    os.makedirs(os.path.join(BASE_DIR, 'logs'), exist_ok=True)
    
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'security': {
                'format': '{asctime} | {levelname} | {message}',
                'style': '{',
                'datefmt': '%Y-%m-%d %H:%M:%S'
            },
            'verbose': {
                'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
                'style': '{',
            },
        },
        'handlers': {
            'security_file': {
                'level': 'INFO',
                'class': 'logging.handlers.RotatingFileHandler',
                'filename': os.path.join(BASE_DIR, 'logs', f'security_{os.getenv("ENVIRONMENT", "dev")}.log'),
                'formatter': 'security',
                'maxBytes': 1024*1024*10,  # 10MB
                'backupCount': 5,
            },
            'console': {
                'level': 'INFO',
                'class': 'logging.StreamHandler',
                'formatter': 'verbose',
            },
        },
        'loggers': {
            'security': {
                'handlers': ['security_file', 'console'],
                'level': 'INFO',
                'propagate': False,
            },
            'django.security': {
                'handlers': ['security_file'],
                'level': 'WARNING',
                'propagate': False,
            },
        },
    }
else:
    # Production (Vercel) - console logging only (no file system writes)
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'security': {
                'format': '[SECURITY] {asctime} | {levelname} | {message}',
                'style': '{',
                'datefmt': '%Y-%m-%d %H:%M:%S'
            },
            'verbose': {
                'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
                'style': '{',
            },
        },
        'handlers': {
            'console': {
                'level': 'INFO',
                'class': 'logging.StreamHandler',
                'formatter': 'security',
            },
        },
        'loggers': {
            'security': {
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': False,
            },
            'django.security': {
                'handlers': ['console'],
                'level': 'WARNING',
                'propagate': False,
            },
        },
    }
