-- Dual user support migration for Supabase
-- Keeps whitelist logic for internal users and allows public supporters.

create extension if not exists pgcrypto;

-- 1) Internal whitelist
create table if not exists public.whitelist (
  email text primary key,
  internal_role text not null check (internal_role in ('leader', 'coleader', 'member')),
  invited_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

-- 2) Unified profiles for all users
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  name text,
  is_internal boolean not null default false,
  internal_role text null check (internal_role in ('leader', 'coleader', 'member')),
  created_at timestamptz not null default now()
);

-- 3) Subscriptions
create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  plan text not null,
  status text not null,
  next_billing_date timestamptz,
  created_at timestamptz not null default now()
);

-- 4) Payments
create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  amount numeric(12,2) not null check (amount > 0),
  currency text not null default 'COP',
  type text not null check (type in ('donation', 'subscription', 'product')),
  status text not null,
  payu_transaction_id text unique,
  created_at timestamptz not null default now()
);

create index if not exists subscriptions_user_id_idx on public.subscriptions(user_id);
create index if not exists payments_user_id_idx on public.payments(user_id);
create index if not exists profiles_is_internal_idx on public.profiles(is_internal);

-- Registration logic: assign internal/external status from whitelist on auth signup.
create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  wl public.whitelist%rowtype;
begin
  select * into wl from public.whitelist where lower(email) = lower(new.email);

  insert into public.profiles (id, email, name, is_internal, internal_role)
  values (
    new.id,
    lower(new.email),
    coalesce(new.raw_user_meta_data ->> 'name', ''),
    wl.email is not null,
    case when wl.email is not null then wl.internal_role else null end
  )
  on conflict (id) do update
  set
    email = excluded.email,
    name = excluded.name,
    is_internal = excluded.is_internal,
    internal_role = excluded.internal_role;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_auth_user();

-- Keep existing users internal by default if they currently exist in whitelist.
update public.profiles p
set
  is_internal = true,
  internal_role = w.internal_role
from public.whitelist w
where lower(p.email) = lower(w.email);

-- RLS policies
alter table public.whitelist enable row level security;
alter table public.profiles enable row level security;
alter table public.subscriptions enable row level security;
alter table public.payments enable row level security;

-- whitelist: only internal leaders/coleaders can manage
drop policy if exists whitelist_select_internal on public.whitelist;
create policy whitelist_select_internal
on public.whitelist
for select
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
      and p.is_internal = true
      and p.internal_role in ('leader', 'coleader')
  )
);

drop policy if exists whitelist_insert_internal on public.whitelist;
create policy whitelist_insert_internal
on public.whitelist
for insert
with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
      and p.is_internal = true
      and p.internal_role in ('leader', 'coleader')
  )
);

drop policy if exists whitelist_update_internal on public.whitelist;
create policy whitelist_update_internal
on public.whitelist
for update
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
      and p.is_internal = true
      and p.internal_role in ('leader', 'coleader')
  )
)
with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
      and p.is_internal = true
      and p.internal_role in ('leader', 'coleader')
  )
);

-- profiles: each user can read/update their own profile
drop policy if exists profiles_self_select on public.profiles;
create policy profiles_self_select
on public.profiles
for select
using (id = auth.uid());

drop policy if exists profiles_self_update on public.profiles;
create policy profiles_self_update
on public.profiles
for update
using (id = auth.uid())
with check (id = auth.uid());

-- subscriptions: user-owned access
drop policy if exists subscriptions_owner_all on public.subscriptions;
create policy subscriptions_owner_all
on public.subscriptions
for all
using (user_id = auth.uid())
with check (user_id = auth.uid());

-- payments: user-owned access
drop policy if exists payments_owner_all on public.payments;
create policy payments_owner_all
on public.payments
for all
using (user_id = auth.uid())
with check (user_id = auth.uid());

-- optional helper function to guard internal endpoints from SQL/RPC
create or replace function public.assert_internal_user()
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.is_internal = true
  );
$$;
